console.log(2 > 1)
console.log(1<2)
console.log(1==2)
console.log(1<=2)
console.log(null > 0)
console.log(null == 0)
console.log(null < 0)
console.log(null >= 0)
console.log(null <= 0)
console.log(null === 0)
// === strict check it check value along with there datatype